baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'OWASP Security Champions Guide'
theme = 'ananke'

[menus]
  [[menus.main]]
    name = 'Introduction'
    pageRef = '/introduction'
    weight = 10
  [[menus.main]]
    name = 'Manifesto'
    pageRef = '/manifesto'
    weight = 20
  [[menus.main]]
    name = 'Principles'
    pageRef = '/principles'
    weight = 30
  [[menus.main]]
    name = 'Maturity model'
    pageRef = '/maturitymodel'
    weight = 40
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 50
  [[menus.main]]
    name = 'Get involved'
    pageRef = '/getinvolved'
    weight = 60

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
