baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'OWASP Security Champions Guide'
theme = 'ananke'

[menus]
  [[menus.main]]
    name = 'Introduction'
    pageRef = '/introduction'
    weight = 10
  [[menus.main]]
    name = 'Manifesto'
    pageRef = '/manifesto'
    weight = 20
  [[menus.main]]
    name = 'Principles'
    pageRef = '/principles'
    weight = 30
  [[menus.main]]
    name = 'Maturity model'
    pageRef = '/maturitymodel/'
    identifier = 'maturitymodel'
    weight = 40
    hasChildren = true
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 50
  [[menus.main]]
    name = 'Get involved'
    pageRef = '/getinvolved'
    weight = 60
  [[menus.main]]
    name = 'Data Driven'
    pageRef = '/datadriven'
    weight = 70

  [[menus.main]]
    name = 'Introduction'
    parent = 'maturitymodel'
    pageRef = '/maturitymodel/introduction'
    weight = 10
  [[menus.main]]
    name = 'Phases'
    parent = 'maturitymodel'
    pageRef = '/maturitymodel/phases'
    weight = 20
  [[menus.main]]
    name = 'Principles'
    parent = 'maturitymodel'
    pageRef = '/maturitymodel/principles'
    weight = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
